name: W3F Education

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish
        run: |
          git config --global user.email "drw3rk@users.noreply.github.com"
          git config --global user.name "DrW3RK"
          echo "machine github.com login DrW3RK password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
          yarn && yarn build && GIT_USER=DrW3RK PUBLISHING=true yarn deploy
